### ISSUE TITLE
Allow to subclass ClickShell

### ISSUE THREAD

**Issue by lambdafu** [clarkperkins/click-shell#22]
Currently, ClickShell is not exported from click_shell, and it is also hardcoded in make_click_shell and Shell. This means that users of click-shell can not subclass ClickShell (and thus Cmd), for example to add custom precmd and postcmd handler.

I guess a straightforward way to implement this would be to allow parametrization of the ClickShell class in the above functions and to export its definition (of course, instead it can be imported from click_shell.core).

**Comment by clarkperkins** [comment]
Hi @lambdafu, thanks for the suggestion! I'll get this included in the next release.
