### ISSUE TITLE
Call on_finished when running traditional command not in shell mode

### ISSUE THREAD

**Issue by bdoyle0182** [clarkperkins/click-shell#25]
Is it possible to make `on_finished` run even if we're running a standard click command without entering the click shell? My cli has resources that are opened when running a command and need to be closed after the single command is finished. It's easy in shell mode having `on_finished`, so would be nice if non-shell single commands could piggy-back and use this as well.

**Comment by clarkperkins** [comment]
Hi there @bdoyle0182, apologies for the very delayed response, but I think this is a great idea. I'll get it included in the next release.
